from SRC.util import *

EXPORT_DIR = 'export'

GENERATE_COUNTS = {
    DRIVERS: 775,
    CONSTRUCTORS: 200,
    SEASONS: 100,
    CIRCUITS: 100
}

DRIVER_GEN_MIN_AGE = 18
DRIVER_GEN_MAX_AGE = 92
DRIVER_GEN_DEATH_AGE = 80
DRIVER_GEN_MAXIMUM_CHAMPIONSHIPS = 2
DRIVER_GEN_MAX_TOTAL_RACE_ENTRIES = 400
DRIVER_GEN_MAX_RACE_WINS = 200
DRIVER_GEN_MAX_POINTS = 5000

SEASON_MIN_YEAR = 1990
SEASON_START_MONTH = '01'
SEASON_START_DAY = '01'
SEASON_END_MONTH = '12'
SEASON_END_DAY = '31'

RACES_PER_SEASON = 20
DRIVERS_PER_RACE = 20
FASTEST_QUALIFYING_TIME_SECONDS = 92.726 # Charles LeClercs fastest time 2023